using LeagueCallerServer.Database;
using LeagueCallerServer.Model;
using Microsoft.AspNetCore.Mvc;

namespace LeagueCallerServer.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class LoLCallerController : ControllerBase
    {
        private readonly LoLCallerDatabaseContext _dbContext;

        public LoLCallerController(LoLCallerDatabaseContext dbContext) { 
        _dbContext = dbContext;
        }


        [HttpPost("register-user", Name = "RegisterUser")]
        public IActionResult RegisterUser([FromBody] User user)
        {
            try
            {
                // check if email and username are valid (are unique)
                var users = _dbContext.Users.ToList();
                foreach (var u in users)
                {
                    if (u.Email == user.Email)
                    {
                        throw new Exception("Email taken");
                    } else if(u.Name ==  user.Name)
                    {
                        throw new Exception("Username taken");
                        
                    }

                }


                // Add the user to the database
                _dbContext.Users.Add(user);

                // Save changes to get the ID generated by the database
                _dbContext.SaveChanges();

                // Return the created user with status 201 Created
                return CreatedAtAction(nameof(GetAllUsers), user);
            }
            catch (Exception ex)
            {
                // Return error if something goes wrong
                return StatusCode(500, $"Error registering user: {ex.Message}");
            }
        }

        [HttpPost("login-user", Name = "LoginUser")]
        public IActionResult LoginUser([FromBody] LoginModel loginModel)
        {
            // Perform login logic here
            var existingUser = _dbContext.Users.FirstOrDefault(u => u.Email == loginModel.Email && u.Password == loginModel.Password);
            if (existingUser == null)
            {
                return BadRequest("Invalid email or password");
            }
            else
            {
                return Ok(existingUser);
            }
        }


        [HttpGet("get-all-users", Name = "GetAllUsers")]
        public IActionResult GetAllUsers()
        {
            try
            {
                var users = _dbContext.Users.ToList();
                return Ok(users);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error getting users: {ex.Message}");
            }
        }


    }
}
